### ISSUE TITLE
Ability to export multiple pages

### ISSUE THREAD

**Issue by NontasBak** [kitschpatrol/tldraw-cli#1]
![image](https://github.com/kitschpatrol/tldraw-cli/assets/117574197/8a6f0270-5238-4b70-b7ab-1cfefeba8b4b)

It would be a nice addition to be able to export multiple pages from a single .tldr file, similar to the way frame exporting is implemented as of writing.

**Comment by kitschpatrol** [comment]
Thanks, agreed — this feature is on the to-do list.

**Comment by kitschpatrol** [comment]
I just looked into this today. It should make it into a release in the next day or two.

**Comment by NontasBak** [comment]
Thank you very much! I'll make sure to check it out

**Comment by kitschpatrol** [comment]
Ok this should be resolved in the just-released version 4.4.

Short version:

There's a new `pages` option, that works pretty much like the `frames` option in that it can take a boolean or an array of page names or ID strings.

Long version:

In addition to passing page names or IDs to `pages`, I think it also makes sense to allow page indices, so arrays of numbers are also allowed as an argument to `pages`. (Note that this argument type isn't available for the `frames` option, since frames are not explicitly ordered due to their two dimensions of freedom on the canvas.)

There's some ambiguity about how to design this API for least surprise while maintaining consistency with the precedents set by the `frames` option.

I think it's a reasonable assumption that by default one `export` command should yield one downloaded image file, though I realize this isn't always intuitive since only the `tldr` format can reasonably represent the multiple pages and frames that might be present in a TLDraw sketch. (At least without getting into more complex multi-page file formats like PDF, which isn't out of the question but is out of scope for this issue and my morning. 😅)

Nevertheless sticking with that idea for now, and if the user wants more complex (multi-file) export behavior, then they'll need to reach for the options.

Unfortunately this does result in a few nuances in terms of how the new `pages` option interacts with the existing `frames` option, which is spelled out in the table below:

|                        | **`pages`** **`undefined`**                                                                   | **`pages`** **`false`**                                                                       | **`pages`** **`true`**                                                                   | **`pages`** **`string[]`**                                                                                          | **`pages`** **`number[]`**                                                                                              |
| ---------------------- | ----------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------- |
| **`frames`** **`undefined`** | Entire first page exported to a single image                                        | Entire first page exported to a single image                                        | Entirety of each page exported to separate images                              | Entirety of each page with matching IDs or names exported to separate images                              | Entirety of each page with matching zero-based index exported to separate images                              |
| **`frames`** **`false`**     | Entire first page exported to a single image                                        | Entire first page exported to a single image                                        | Entirety of each page exported to separate images                              | Entirety of each page with matching IDs or names exported to separate images                              | Entirety of each page with matching zero-based index exported to separate images                              |
| **`frames`** **`true`**      | Each frame of first page exported to separate images                                | Each frame of first page exported to separate images                                | Each frame of each page exported to separate images                            | Each frame of each page with matching IDs or names exported to separate images                            | Each frame of each page with matching zero-based index exported to separate images                            |
| **`frames`** **`string[]`**  | Each frame with matching IDs or names on the first page exported to separate images | Each frame with matching IDs or names on the first page exported to separate images | Each frame with matching IDs or names on each page exported to separate images | Each frame with matching IDs or names of each page with matching IDs or names exported to separate images | Each frame with matching IDs or names of each page with matching zero-based index exported to separate images |
