### ISSUE TITLE
Add a recipes/common-workflows section to the README for export-on-save

### ISSUE THREAD

**Issue by foot** [kitschpatrol/tldraw-cli#15]
Hello!

Having a great time w/ the cli 🎉 . Works well with the vscode extension. My flow has been:

1. Edit `foo.tldr` in vscode w/ the tldr extension.
2. Switch to terminal / vscode-term
3. Run `make` [0]

Some kind of "export on save" would be very cool. Possible options:

1. Use some kind of watch helper `npm-watch` (?) etc, not sure what works best these days
2. Some watch command built in `npx @kitschpatrol/tldraw-cli --watch *.tldr`
3. a vscode config snippet that triggers on-save would be cool too.
4. ?
 
Have you tried anything like this?

[0]
```makefile
# Define a target to rebuild all svg files from the tldr files
SVG_FILES := $(patsubst %.tldr,%.svg,$(wildcard *.tldr))

all: svg

svg: $(SVG_FILES)

%.svg: %.tldr
	npx @kitschpatrol/tldraw-cli export $<


.PHONY: force-rebuild
force-rebuild:
	npx @kitschpatrol/tldraw-cli export $(wildcard *.tldr)
```

**Comment by kitschpatrol** [comment]
Thanks! Glad to hear it's working well for you.

Though I agree it would be convenient, I probably won't add `--watch` to the core CLI tool for now just because of the maintenance overhead and the cross-platform complexities, but I think there are lots of viable approaches to accomplish similar results with external tools like you've described.

For your specific workflow, since you're already in VS Code, I think finding a decent "run on save" extension might be easiest? [pucelle.run-on-save](https://marketplace.visualstudio.com/items?itemName=pucelle.run-on-save) looks reasonably fresh, but it's been a few years since I've needed such an extension, so your search is as good as mine. 😅 

Also, I know I already mentioned [vite-plugin-tldraw](https://github.com/kitschpatrol/vite-plugin-tldraw) in the other issue, but if you happen to have a vite-based workflow, this will give you watch-like functionality "for free" when you run a vite dev server.

I'm happy to add a section about this to the readme

**Comment by kitschpatrol** [comment]
Hi again, I did some quick tests and found the following:

## Pure CLI tool approach

For something easily accessible from NPM, [nodemon](https://github.com/remy/nodemon) seemed promising, but doesn't have a way to pass the modified file(s) as an argument purely through the CLI without writing a separate script.

The most-used library for _implementing_ watchers seems to be [Chokidar](https://www.npmjs.com/package/chokidar). A CLI, isn't a core project, but there's a slightly under-maintained CLI package named [`chokadir-cli`](https://www.npmjs.com/package/chokidar-cli) which actually seems to work well.

The following command will export `.tldr` to `.svg` whenever a file changes:

```sh
npx chokidar-cli "**/*.tldr" -c "npx @kitschpatrol/tldraw-cli export {path}"
```

(It's tempting to fold the Chokadir library it into `tldraw-cli`, but it's on the cusp up a major update so I might see when / where that lands first.)

Your `make` example is very cool, but `make` is maybe a bit esoteric for inclusion in the readme since I expect most devs working with tldraw and grabbing tools like this from NPM are going to be most familiar with web-centric tools.

## VS Code extension approach

The [pucelle.run-on-save](https://marketplace.visualstudio.com/items?itemName=pucelle.run-on-save) that I thought might be suited to this task actually doesn't detect "save" events initated by the tldraw VS Code plugin... but I did find one that works by detecting file "change" events instead of "save" events.: [appulate.filewatcher](https://marketplace.visualstudio.com/items?itemName=appulate.filewatcher)

It works fine with the following configuration:

```json
{
  "filewatcher.commands": [
    {
      "match": "\\.tldr",
      "isAsync": true,
      "cmd": "cd ${workspaceRoot} && npx @kitschpatrol/tldraw-cli export ${file}",
      "event": "onFileChange"
    }
  ]
}
```

Hope that's helpful. I'll probably add notes about the `chokadir-cli`, `appulate.filewatcher`, and `vite-plugin-tldraw` approaches to the readme.

**Comment by kitschpatrol** [comment]
I've added some guidance to the readme. Please feel free to reopen if you'd like to discuss further.
