### ISSUE TITLE
Support for svg's that work in _both_ dark and light mode?

### ISSUE THREAD

**Issue by foot** [kitschpatrol/tldraw-cli#16]
### Use case

This might be a bit of a niche use case. We're using `tldraw-cli export` to generate SVG diagrams that are included in github markdown docs pages. Sometimes they'll be rendered in github dark mode, and other times in github light mode.

### Existing functionality

`tldraw-cli export --dark` is already there!

### Proposed extension

`tldraw-cli export --system-color-mode` that uses `@media (prefers-color-scheme: dark)` to make an svg that can be rendered differently depending on whether the system/browsre is currently in dark or light mode?

**Comment by kitschpatrol** [comment]
Hi, thanks, this is a great idea!

However, looking at the [structure of an SVG coming from tldraw](https://gist.github.com/kitschpatrol/f40fb11e84ef70dd93f1baa335882c3a?short_path=70c9c7e) doesn't give me a lot of hope that this would be easy to do, since it looks like thematic color information is embedded directly in the element attributes and not managed through an inline stylesheet.

Without clean separation of style in the existing SVGs, I'm not sure of a way to actually implement this that would work reliably. Some approaches that come to mind:

- Extraction of theme values from element attributes into a `<style>` element. (Impossibly brittle.)
- Merge the entire light and dark SVG markup into one file with some kind of top-level visibility conditional behind the `media` query. (Doubles both the size of the SVGs and the export time, and also seems pretty brittle.)

Are there other approaches I'm not thinking of?

---

For what it's worth, I've been accomplishing something similar in HTML instead, using the `<picture>` element with multiple `<source>`s containing light and dark image variations generated by `tldraw-cli export`. It's not as clean or as nice as having a single responsive SVG would be, but it avoids the pitfalls of trying to manipulate the SVG output from `tldraw`:

```html
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="something-dark.svg">
  <source media="(prefers-color-scheme: light)" srcset="something-light.svg">
  <img alt="something" src="something-light.svg">
</picture>
```

My readme-templating tool [`mdat`](https://github.com/kitschpatrol/mdat) uses this approach to automatically [embed `.tldr` files](https://github.com/kitschpatrol/mdat/blob/ba9f0eac3814d228209b832032bea60f7cebc873/src/lib/readme/rules/tldraw.ts#L100-L122) in readme Markdown.

I'm also doing something similar in the asset pipeline of a static site generator using [vite-plugin-tldraw](https://github.com/kitschpatrol/vite-plugin-tldraw) to populate the `<picture>` element, happy to share examples of that if helpful.

**Comment by kitschpatrol** [comment]
Closing this due to the issues with the possible implementation approaches I mentioned above. Recommending the external `<picture>` element strategy for most cases where dark and light mode images are required.

Please reopen if a more tractable implementation strategy is identified.
