### ISSUE TITLE
Error: Cannot export an empty document while .tldr file isn't empty

### ISSUE THREAD

**Issue by NontasBak** [kitschpatrol/tldraw-cli#2]
I'm trying to run some tests on my program but it crashes when its about to export the .tldr file. This is not always the case since I didn't have this problem a few days ago. I couldn't manage to convert the file with the cli commands as well, so I doubt the problem has to do with my code.

I also don't think the file is corrupted since I can open and export it normally on tldraw.com.

If you cannot replicate this issue and want to test with my .tldr file go to https://github.com/NontasBak/sapiloguide/tree/testing-exporting-error/src/lesson1 and download `2020-feb.tldr` (the other file `2020-sep.tldr` works fine btw)

```
> npm start
[Error] [Browser] Couldn't parse tldr file: migrationFailed
file:///home/nontas/Projects/sapiloguide/node_modules/@kitschpatrol/tldraw-cli/dist/lib/index.js:17062
      throw new Error("Cannot export an empty document");
            ^

Error: Cannot export an empty document
    at TldrawController.download (file:///home/nontas/Projects/sapiloguide/node_modules/@kitschpatrol/tldraw-cli/dist/lib/index.js:17062:13)
    at tldrawToImage (file:///home/nontas/Projects/sapiloguide/node_modules/@kitschpatrol/tldraw-cli/dist/lib/index.js:17599:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async convertTldrToImages (file:///home/nontas/Projects/sapiloguide/main.js:68:23)
    at async build (file:///home/nontas/Projects/sapiloguide/main.js:20:13)

Node.js v20.11.1```

**Comment by kitschpatrol** [comment]
Thanks, I'll take a look at this.

**Comment by kitschpatrol** [comment]
Quick update:

The issue here seems to be that the local version of tldraw used in tldraw-cli can't load tldr files saved by the latest version of tldraw.com.

Specifically, the shape record version:

- `2020-sep.tldr` has [`schema.recordVersions.shape.version: 3`](https://github.com/NontasBak/sapiloguide/blob/0eca69df96d13bec100a8577967591ae85b994d9/src/lesson1/2020-sep.tldr#L32) and loads fine
- `2020-feb.tldr` has [`schema.recordVersions.shape.version: 4`](https://github.com/NontasBak/sapiloguide/blob/0eca69df96d13bec100a8577967591ae85b994d9/src/lesson1/2020-feb.tldr#L32) and fails to load

I'm guessing this is from a recent update to the tldraw.com site which hasn't made it into a release of the tldraw library itself. (tldraw-cli is already using the latest release, which seems to predate shape version 4.)

I'll think about the right approach and keep you posted here. Tricky spot since tldraw.com interoperability is obviously critical, but embedding non-release versions of tldraw doesn't seem especially great. But will probably have to do that. 😅

(There's also a big change to [tldraw's migration strategy](https://github.com/tldraw/tldraw/commit/4f70a4f4e85b278e79a4afadec2eeb08f26879a8) in the pipeline which could create some additional bumps.)

**Comment by kitschpatrol** [comment]
Ok, I just cut a [new release v4.5.2](https://github.com/kitschpatrol/tldraw-cli/releases/tag/v4.5.2) which uses a pre-release version of tldraw (2.1) for local operations.

The library should work now with `2020-feb.tldr` (and other shape version 4 files), let me know if it's a fix for you.

**Comment by NontasBak** [comment]
It did get fixed with the latest update fortunately, thank you again for your help 🙏 

So from what I understand they pushed this experimental 2.1 version (to a subset of users?) and this is what's making the `2020-feb.tldr` file throw an error.

**Comment by kitschpatrol** [comment]
Hey Nontas, just FYI I saw migration issues again recently in the latest tldraw.com "schema version 2" files.

Just fixed it in tldraw-cli 4.5.3 which updates to one of the tldraw 2.2.0 canary releases.

**Comment by NontasBak** [comment]
Thanks for the update!

**Comment by NontasBak** [comment]
Hey @kitschpatrol ! Is it possible you can update the tldraw version to a newer canary one? I cannot export unfortunately:( Here's a .tldr file if you want to test for yourself
[2021-sep.zip](https://github.com/user-attachments/files/15766148/2021-sep.zip)

**Comment by kitschpatrol** [comment]
Hey Nontas, yes I'll take a look at this today.

**Comment by kitschpatrol** [comment]
Ok, Should be fixed in [the latest release v4.5.5](https://github.com/kitschpatrol/tldraw-cli/releases/tag/v4.5.5).

It's working now on my end with 2021-sep.tldr, let me know if it's a fix for you.

Thanks for bringing this to my attention and providing a test file.

I should really run the test suite on a schedule...

**Comment by NontasBak** [comment]
Thank you very much! Works perfectly 👌Also thank you for your continuous support!

**Comment by kitschpatrol** [comment]
Glad it's working! I just added a daily test action, hoping to catch the next API breakage more quickly. 🤞
